POST http://localhost:4000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Anjrot",
  "username": "AnjrotDev000",
  "email": "example3@test.com",
  "password": "12345456"
}

###
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "example3@test.com",
  "password": "12345456"
}
