POST http://localhost:4000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "test",
  "username": "test",
  "email": "test@test.com",
  "password": "123456"
}

###
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}
